import { NextRequest } from 'next/server'
import { requireAuth, apiResponse, apiError, handleApiError } from '@/lib/api-utils'
import { db } from '@/lib/db'

// GET /api/export - Export timetable data
export async function GET(request: NextRequest) {
  try {
    const authResult = await requireAuth()
    if ('error' in authResult) {
      return apiError(authResult.error, authResult.status)
    }

    const { searchParams } = new URL(request.url)
    const examPeriodId = searchParams.get('examPeriodId')
    const format = searchParams.get('format') || 'json'

    if (!examPeriodId) {
      return apiError('Exam period ID is required')
    }

    // Get exam period with all slots
    const examPeriod = await db.examPeriod.findUnique({
      where: { id: examPeriodId },
      include: {
        institution: true,
        examSlots: {
          include: {
            course: {
              include: {
                department: { select: { code: true, name: true } },
                _count: { select: { studentCourses: { where: { status: { in: ['REGISTERED', 'CARRY_OVER', 'SPILLOVER'] } } } } },
              },
            },
            room: true,
          },
          orderBy: [{ date: 'asc' }, { slotNumber: 'asc' }],
        },
      },
    })

    if (!examPeriod) {
      return apiError('Exam period not found', 404)
    }

    if (format === 'json') {
      return apiResponse(examPeriod)
    }

    // For CSV/text format - create a simple text timetable
    if (format === 'csv' || format === 'txt') {
      const lines: string[] = []
      lines.push(`${examPeriod.institution.name}`)
      lines.push(`${examPeriod.name} - ${examPeriod.session} (Semester ${examPeriod.semester})`)
      lines.push('='.repeat(80))
      lines.push('')

      // Group by date
      const byDate = examPeriod.examSlots.reduce((acc, slot) => {
        const date = new Date(slot.date).toLocaleDateString('en-GB', {
          weekday: 'long',
          day: 'numeric',
          month: 'long',
          year: 'numeric',
        })
        if (!acc[date]) acc[date] = []
        acc[date].push(slot)
        return acc
      }, {} as Record<string, typeof examPeriod.examSlots>)

      for (const [date, slots] of Object.entries(byDate)) {
        lines.push(`📅 ${date}`)
        lines.push('-'.repeat(60))

        const slotGroups = {
          1: slots.filter(s => s.slotNumber === 1),
          2: slots.filter(s => s.slotNumber === 2),
          3: slots.filter(s => s.slotNumber === 3),
        }

        const slotNames = ['MORNING', 'AFTERNOON', 'EVENING']

        for (let i = 1; i <= 3; i++) {
          if (slotGroups[i as 1|2|3].length > 0) {
            lines.push(`  🕐 ${slotNames[i-1]} (${i === 1 ? examPeriod.morningStart + '-' + examPeriod.morningEnd : i === 2 ? examPeriod.afternoonStart + '-' + examPeriod.afternoonEnd : examPeriod.eveningStart + '-' + examPeriod.eveningEnd})`)

            for (const slot of slotGroups[i as 1|2|3]) {
              lines.push(`     • ${slot.course.code}: ${slot.course.name}`)
              lines.push(`       Room: ${slot.room.name} (${slot.room.code}) | Students: ${slot.course._count?.studentCourses || 0}`)
            }
            lines.push('')
          }
        }
        lines.push('')
      }

      lines.push('='.repeat(80))
      lines.push(`Generated by ClashFree on ${new Date().toLocaleString()}`)

      return new Response(lines.join('\n'), {
        headers: {
          'Content-Type': 'text/plain',
          'Content-Disposition': `attachment; filename="timetable-${examPeriod.session.replace('/', '-')}-sem${examPeriod.semester}.txt"`,
        },
      })
    }

    return apiResponse(examPeriod)
  } catch (error) {
    return handleApiError(error)
  }
}
