// ============================================================
// FEDKO DEMO DATA — COURSES (CCMAS-Aligned)
// 8 courses/semester × 2 semesters × 4 years = 64 per dept
// CU legend: 1CU=1x/wk | 2CU=2x/wk | 3CU=2x/wk+1 | 4CU=2x/wk
// ============================================================

export interface Course {
  code: string;
  title: string;
  creditUnit: number;
  level: 100 | 200 | 300 | 400;
  semester: 1 | 2;
  dept: string;        // dept code or "GNS"/"GST" for general studies
  isGeneral?: boolean; // GST/GNS courses taken by multiple depts
  type: "core" | "elective" | "general" | "practical";
  hoursPerWeek: number; // 1CU→1, 2CU→2, 3CU→3, 4CU→2(+extra practical)
}

// ── GENERAL STUDIES (shared across all SCI depts) ────────────
export const GST_COURSES: Course[] = [
  // 100L S1
  { code: "GST 111", title: "Communication in English I", creditUnit: 2, level: 100, semester: 1, dept: "GST", isGeneral: true, type: "general", hoursPerWeek: 2 },
  { code: "GST 112", title: "Logic, Philosophy and Human Existence", creditUnit: 2, level: 100, semester: 1, dept: "GST", isGeneral: true, type: "general", hoursPerWeek: 2 },
  { code: "GST 113", title: "Nigerian Peoples and Culture", creditUnit: 2, level: 100, semester: 1, dept: "GST", isGeneral: true, type: "general", hoursPerWeek: 2 },
  // 100L S2
  { code: "GST 121", title: "Communication in English II", creditUnit: 2, level: 100, semester: 2, dept: "GST", isGeneral: true, type: "general", hoursPerWeek: 2 },
  { code: "GST 122", title: "Use of Library, Study Skills and ICT", creditUnit: 2, level: 100, semester: 2, dept: "GST", isGeneral: true, type: "general", hoursPerWeek: 2 },
  { code: "GST 123", title: "History and Philosophy of Science", creditUnit: 2, level: 100, semester: 2, dept: "GST", isGeneral: true, type: "general", hoursPerWeek: 2 },
  // 200L
  { code: "GST 211", title: "Entrepreneurship I", creditUnit: 2, level: 200, semester: 1, dept: "GST", isGeneral: true, type: "general", hoursPerWeek: 2 },
  { code: "GST 212", title: "Peace and Conflict Resolution", creditUnit: 2, level: 200, semester: 2, dept: "GST", isGeneral: true, type: "general", hoursPerWeek: 2 },
  // 300L
  { code: "GST 311", title: "Entrepreneurship II", creditUnit: 2, level: 300, semester: 1, dept: "GST", isGeneral: true, type: "general", hoursPerWeek: 2 },
  { code: "GST 312", title: "Leadership, Governance and Society", creditUnit: 2, level: 300, semester: 2, dept: "GST", isGeneral: true, type: "general", hoursPerWeek: 2 },
];

// ── CHEMISTRY ────────────────────────────────────────────────
export const CHM_COURSES: Course[] = [
  // 100L S1
  { code: "CHM 101", title: "General Chemistry I", creditUnit: 3, level: 100, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 103", title: "Practical Chemistry I", creditUnit: 1, level: 100, semester: 1, dept: "CHM", type: "practical", hoursPerWeek: 1 },
  { code: "MTH 101", title: "Elementary Mathematics I", creditUnit: 3, level: 100, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "PHY 101", title: "General Physics I", creditUnit: 3, level: 100, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "PHY 107", title: "General Physics Practical I", creditUnit: 1, level: 100, semester: 1, dept: "CHM", type: "practical", hoursPerWeek: 1 },
  { code: "GST 111", title: "Communication in English I", creditUnit: 2, level: 100, semester: 1, dept: "CHM", type: "general", hoursPerWeek: 2 },
  { code: "GST 112", title: "Logic, Philosophy and Human Existence", creditUnit: 2, level: 100, semester: 1, dept: "CHM", type: "general", hoursPerWeek: 2 },
  { code: "GST 113", title: "Nigerian Peoples and Culture", creditUnit: 2, level: 100, semester: 1, dept: "CHM", type: "general", hoursPerWeek: 2 },
  // 100L S2
  { code: "CHM 102", title: "General Chemistry II", creditUnit: 3, level: 100, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 104", title: "Practical Chemistry II", creditUnit: 1, level: 100, semester: 2, dept: "CHM", type: "practical", hoursPerWeek: 1 },
  { code: "MTH 102", title: "Elementary Mathematics II", creditUnit: 3, level: 100, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "PHY 102", title: "General Physics II", creditUnit: 3, level: 100, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "PHY 108", title: "General Physics Practical II", creditUnit: 1, level: 100, semester: 2, dept: "CHM", type: "practical", hoursPerWeek: 1 },
  { code: "GST 121", title: "Communication in English II", creditUnit: 2, level: 100, semester: 2, dept: "CHM", type: "general", hoursPerWeek: 2 },
  { code: "GST 122", title: "Use of Library, Study Skills and ICT", creditUnit: 2, level: 100, semester: 2, dept: "CHM", type: "general", hoursPerWeek: 2 },
  { code: "GST 123", title: "History and Philosophy of Science", creditUnit: 2, level: 100, semester: 2, dept: "CHM", type: "general", hoursPerWeek: 2 },
  // 200L S1
  { code: "CHM 211", title: "Organic Chemistry I", creditUnit: 3, level: 200, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 213", title: "Inorganic Chemistry I", creditUnit: 3, level: 200, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 215", title: "Physical Chemistry I", creditUnit: 3, level: 200, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 217", title: "Analytical Chemistry I", creditUnit: 2, level: 200, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 2 },
  { code: "CHM 219", title: "Practical Chemistry III", creditUnit: 2, level: 200, semester: 1, dept: "CHM", type: "practical", hoursPerWeek: 2 },
  { code: "MTH 211", title: "Mathematical Methods I", creditUnit: 3, level: 200, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "BCH 201", title: "Introduction to Biochemistry", creditUnit: 2, level: 200, semester: 1, dept: "CHM", type: "elective", hoursPerWeek: 2 },
  { code: "GST 211", title: "Entrepreneurship I", creditUnit: 2, level: 200, semester: 1, dept: "CHM", type: "general", hoursPerWeek: 2 },
  // 200L S2
  { code: "CHM 212", title: "Organic Chemistry II", creditUnit: 3, level: 200, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 214", title: "Inorganic Chemistry II", creditUnit: 3, level: 200, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 216", title: "Physical Chemistry II", creditUnit: 3, level: 200, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 218", title: "Analytical Chemistry II", creditUnit: 2, level: 200, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 2 },
  { code: "CHM 220", title: "Practical Chemistry IV", creditUnit: 2, level: 200, semester: 2, dept: "CHM", type: "practical", hoursPerWeek: 2 },
  { code: "MTH 212", title: "Mathematical Methods II", creditUnit: 3, level: 200, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "STA 211", title: "Statistics for Physical Sciences", creditUnit: 2, level: 200, semester: 2, dept: "CHM", type: "elective", hoursPerWeek: 2 },
  { code: "GST 212", title: "Peace and Conflict Resolution", creditUnit: 2, level: 200, semester: 2, dept: "CHM", type: "general", hoursPerWeek: 2 },
  // 300L S1
  { code: "CHM 311", title: "Organic Chemistry III (Reaction Mechanisms)", creditUnit: 3, level: 300, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 313", title: "Inorganic Chemistry III (Coordination)", creditUnit: 3, level: 300, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 315", title: "Physical Chemistry III (Thermodynamics)", creditUnit: 3, level: 300, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 317", title: "Instrumental Methods of Analysis", creditUnit: 3, level: 300, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 319", title: "Practical Chemistry V", creditUnit: 2, level: 300, semester: 1, dept: "CHM", type: "practical", hoursPerWeek: 2 },
  { code: "CHM 321", title: "Industrial Chemistry I", creditUnit: 2, level: 300, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 2 },
  { code: "CHM 323", title: "Environmental Chemistry", creditUnit: 2, level: 300, semester: 1, dept: "CHM", type: "elective", hoursPerWeek: 2 },
  { code: "GST 311", title: "Entrepreneurship II", creditUnit: 2, level: 300, semester: 1, dept: "CHM", type: "general", hoursPerWeek: 2 },
  // 300L S2
  { code: "CHM 312", title: "Organic Chemistry IV (Spectroscopy)", creditUnit: 3, level: 300, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 314", title: "Inorganic Chemistry IV (Bioinorganic)", creditUnit: 3, level: 300, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 316", title: "Physical Chemistry IV (Quantum)", creditUnit: 3, level: 300, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 318", title: "Practical Chemistry VI", creditUnit: 2, level: 300, semester: 2, dept: "CHM", type: "practical", hoursPerWeek: 2 },
  { code: "CHM 320", title: "Nuclear and Radiochemistry", creditUnit: 2, level: 300, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 2 },
  { code: "CHM 322", title: "Industrial Chemistry II", creditUnit: 2, level: 300, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 2 },
  { code: "CHM 324", title: "Polymer Chemistry", creditUnit: 2, level: 300, semester: 2, dept: "CHM", type: "elective", hoursPerWeek: 2 },
  { code: "GST 312", title: "Leadership, Governance and Society", creditUnit: 2, level: 300, semester: 2, dept: "CHM", type: "general", hoursPerWeek: 2 },
  // 400L S1
  { code: "CHM 411", title: "Advanced Organic Chemistry", creditUnit: 3, level: 400, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 413", title: "Advanced Inorganic Chemistry", creditUnit: 3, level: 400, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 415", title: "Advanced Physical Chemistry", creditUnit: 3, level: 400, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 417", title: "Research Methodology in Chemistry", creditUnit: 2, level: 400, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 2 },
  { code: "CHM 419", title: "Practical Chemistry VII", creditUnit: 2, level: 400, semester: 1, dept: "CHM", type: "practical", hoursPerWeek: 2 },
  { code: "CHM 421", title: "Petroleum and Petrochemical Chemistry", creditUnit: 2, level: 400, semester: 1, dept: "CHM", type: "elective", hoursPerWeek: 2 },
  { code: "CHM 423", title: "Food and Agricultural Chemistry", creditUnit: 2, level: 400, semester: 1, dept: "CHM", type: "elective", hoursPerWeek: 2 },
  { code: "CHM 491", title: "Project I (Research Proposal)", creditUnit: 3, level: 400, semester: 1, dept: "CHM", type: "core", hoursPerWeek: 3 },
  // 400L S2
  { code: "CHM 412", title: "Photochemistry and Electrochemistry", creditUnit: 3, level: 400, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 414", title: "Medicinal and Pharmaceutical Chemistry", creditUnit: 3, level: 400, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 416", title: "Chemical Thermodynamics and Kinetics", creditUnit: 3, level: 400, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 3 },
  { code: "CHM 418", title: "Chemometrics and Data Analysis", creditUnit: 2, level: 400, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 2 },
  { code: "CHM 420", title: "Practical Chemistry VIII", creditUnit: 2, level: 400, semester: 2, dept: "CHM", type: "practical", hoursPerWeek: 2 },
  { code: "CHM 422", title: "Surface and Colloid Chemistry", creditUnit: 2, level: 400, semester: 2, dept: "CHM", type: "elective", hoursPerWeek: 2 },
  { code: "CHM 424", title: "Computational Chemistry", creditUnit: 2, level: 400, semester: 2, dept: "CHM", type: "elective", hoursPerWeek: 2 },
  { code: "CHM 492", title: "Project II (Final Research Report)", creditUnit: 6, level: 400, semester: 2, dept: "CHM", type: "core", hoursPerWeek: 6 },
];

// ── PHYSICS ──────────────────────────────────────────────────
export const PHY_COURSES: Course[] = [
  // 100L
  { code: "PHY 101", title: "General Physics I (Mechanics)", creditUnit: 3, level: 100, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 103", title: "Heat, Waves and Optics", creditUnit: 3, level: 100, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 107", title: "General Physics Practical I", creditUnit: 1, level: 100, semester: 1, dept: "PHY", type: "practical", hoursPerWeek: 1 },
  { code: "MTH 101", title: "Elementary Mathematics I (Calculus)", creditUnit: 3, level: 100, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "CHM 101", title: "General Chemistry I", creditUnit: 3, level: 100, semester: 1, dept: "PHY", type: "elective", hoursPerWeek: 3 },
  { code: "GST 111", title: "Communication in English I", creditUnit: 2, level: 100, semester: 1, dept: "PHY", type: "general", hoursPerWeek: 2 },
  { code: "GST 112", title: "Logic, Philosophy and Human Existence", creditUnit: 2, level: 100, semester: 1, dept: "PHY", type: "general", hoursPerWeek: 2 },
  { code: "GST 113", title: "Nigerian Peoples and Culture", creditUnit: 2, level: 100, semester: 1, dept: "PHY", type: "general", hoursPerWeek: 2 },
  { code: "PHY 102", title: "General Physics II (Electromagnetism)", creditUnit: 3, level: 100, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 104", title: "Modern Physics I", creditUnit: 3, level: 100, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 108", title: "General Physics Practical II", creditUnit: 1, level: 100, semester: 2, dept: "PHY", type: "practical", hoursPerWeek: 1 },
  { code: "MTH 102", title: "Elementary Mathematics II (Algebra)", creditUnit: 3, level: 100, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "CHM 102", title: "General Chemistry II", creditUnit: 2, level: 100, semester: 2, dept: "PHY", type: "elective", hoursPerWeek: 2 },
  { code: "GST 121", title: "Communication in English II", creditUnit: 2, level: 100, semester: 2, dept: "PHY", type: "general", hoursPerWeek: 2 },
  { code: "GST 122", title: "Use of Library, Study Skills and ICT", creditUnit: 2, level: 100, semester: 2, dept: "PHY", type: "general", hoursPerWeek: 2 },
  { code: "GST 123", title: "History and Philosophy of Science", creditUnit: 2, level: 100, semester: 2, dept: "PHY", type: "general", hoursPerWeek: 2 },
  // 200L
  { code: "PHY 211", title: "Classical Mechanics", creditUnit: 3, level: 200, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 213", title: "Electromagnetism I", creditUnit: 3, level: 200, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 215", title: "Mathematical Methods for Physics I", creditUnit: 3, level: 200, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 217", title: "Electronics I", creditUnit: 3, level: 200, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 219", title: "Physics Practical III", creditUnit: 2, level: 200, semester: 1, dept: "PHY", type: "practical", hoursPerWeek: 2 },
  { code: "MTH 211", title: "Mathematical Methods I", creditUnit: 3, level: 200, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "CSC 201", title: "Introduction to Computer Science", creditUnit: 2, level: 200, semester: 1, dept: "PHY", type: "elective", hoursPerWeek: 2 },
  { code: "GST 211", title: "Entrepreneurship I", creditUnit: 2, level: 200, semester: 1, dept: "PHY", type: "general", hoursPerWeek: 2 },
  { code: "PHY 212", title: "Electromagnetism II", creditUnit: 3, level: 200, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 214", title: "Thermodynamics and Statistical Mechanics", creditUnit: 3, level: 200, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 216", title: "Mathematical Methods for Physics II", creditUnit: 3, level: 200, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 218", title: "Electronics II", creditUnit: 3, level: 200, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 220", title: "Physics Practical IV", creditUnit: 2, level: 200, semester: 2, dept: "PHY", type: "practical", hoursPerWeek: 2 },
  { code: "MTH 212", title: "Mathematical Methods II", creditUnit: 3, level: 200, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "STA 211", title: "Statistics for Physical Sciences", creditUnit: 2, level: 200, semester: 2, dept: "PHY", type: "elective", hoursPerWeek: 2 },
  { code: "GST 212", title: "Peace and Conflict Resolution", creditUnit: 2, level: 200, semester: 2, dept: "PHY", type: "general", hoursPerWeek: 2 },
  // 300L
  { code: "PHY 311", title: "Quantum Mechanics I", creditUnit: 3, level: 300, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 313", title: "Solid State Physics I", creditUnit: 3, level: 300, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 315", title: "Optics and Photonics", creditUnit: 3, level: 300, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 317", title: "Classical Waves", creditUnit: 3, level: 300, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 319", title: "Physics Practical V", creditUnit: 2, level: 300, semester: 1, dept: "PHY", type: "practical", hoursPerWeek: 2 },
  { code: "PHY 321", title: "Introduction to Geophysics", creditUnit: 2, level: 300, semester: 1, dept: "PHY", type: "elective", hoursPerWeek: 2 },
  { code: "PHY 323", title: "Fluid Mechanics", creditUnit: 2, level: 300, semester: 1, dept: "PHY", type: "elective", hoursPerWeek: 2 },
  { code: "GST 311", title: "Entrepreneurship II", creditUnit: 2, level: 300, semester: 1, dept: "PHY", type: "general", hoursPerWeek: 2 },
  { code: "PHY 312", title: "Quantum Mechanics II", creditUnit: 3, level: 300, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 314", title: "Solid State Physics II", creditUnit: 3, level: 300, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 316", title: "Nuclear and Particle Physics", creditUnit: 3, level: 300, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 318", title: "Computational Physics", creditUnit: 3, level: 300, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 320", title: "Physics Practical VI", creditUnit: 2, level: 300, semester: 2, dept: "PHY", type: "practical", hoursPerWeek: 2 },
  { code: "PHY 322", title: "Atmospheric Physics", creditUnit: 2, level: 300, semester: 2, dept: "PHY", type: "elective", hoursPerWeek: 2 },
  { code: "PHY 324", title: "Medical Physics", creditUnit: 2, level: 300, semester: 2, dept: "PHY", type: "elective", hoursPerWeek: 2 },
  { code: "GST 312", title: "Leadership, Governance and Society", creditUnit: 2, level: 300, semester: 2, dept: "PHY", type: "general", hoursPerWeek: 2 },
  // 400L
  { code: "PHY 411", title: "Advanced Quantum Mechanics", creditUnit: 3, level: 400, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 413", title: "Advanced Statistical Mechanics", creditUnit: 3, level: 400, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 415", title: "Plasma Physics", creditUnit: 3, level: 400, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 417", title: "Laser Physics and Applications", creditUnit: 2, level: 400, semester: 1, dept: "PHY", type: "elective", hoursPerWeek: 2 },
  { code: "PHY 419", title: "Physics Practical VII", creditUnit: 2, level: 400, semester: 1, dept: "PHY", type: "practical", hoursPerWeek: 2 },
  { code: "PHY 421", title: "Reactor Physics", creditUnit: 2, level: 400, semester: 1, dept: "PHY", type: "elective", hoursPerWeek: 2 },
  { code: "PHY 423", title: "Research Methods in Physics", creditUnit: 2, level: 400, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 2 },
  { code: "PHY 491", title: "Project I", creditUnit: 3, level: 400, semester: 1, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 412", title: "General Theory of Relativity", creditUnit: 3, level: 400, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 414", title: "Astrophysics and Cosmology", creditUnit: 3, level: 400, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 416", title: "Advanced Electronics", creditUnit: 3, level: 400, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 3 },
  { code: "PHY 418", title: "Energy and Environment", creditUnit: 2, level: 400, semester: 2, dept: "PHY", type: "elective", hoursPerWeek: 2 },
  { code: "PHY 420", title: "Physics Practical VIII", creditUnit: 2, level: 400, semester: 2, dept: "PHY", type: "practical", hoursPerWeek: 2 },
  { code: "PHY 422", title: "Semiconductor Devices", creditUnit: 2, level: 400, semester: 2, dept: "PHY", type: "elective", hoursPerWeek: 2 },
  { code: "PHY 424", title: "Condensed Matter Physics", creditUnit: 2, level: 400, semester: 2, dept: "PHY", type: "elective", hoursPerWeek: 2 },
  { code: "PHY 492", title: "Project II (Final Dissertation)", creditUnit: 6, level: 400, semester: 2, dept: "PHY", type: "core", hoursPerWeek: 6 },
];

// ── COMPUTER SCIENCE ─────────────────────────────────────────
export const CSC_COURSES: Course[] = [
  // 100L
  { code: "CSC 101", title: "Introduction to Computer Science", creditUnit: 2, level: 100, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 2 },
  { code: "CSC 103", title: "Fundamentals of Programming", creditUnit: 3, level: 100, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "MTH 101", title: "Elementary Mathematics I", creditUnit: 3, level: 100, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "PHY 101", title: "General Physics I", creditUnit: 3, level: 100, semester: 1, dept: "CSC", type: "elective", hoursPerWeek: 3 },
  { code: "PHY 107", title: "General Physics Practical I", creditUnit: 1, level: 100, semester: 1, dept: "CSC", type: "practical", hoursPerWeek: 1 },
  { code: "GST 111", title: "Communication in English I", creditUnit: 2, level: 100, semester: 1, dept: "CSC", type: "general", hoursPerWeek: 2 },
  { code: "GST 112", title: "Logic, Philosophy and Human Existence", creditUnit: 2, level: 100, semester: 1, dept: "CSC", type: "general", hoursPerWeek: 2 },
  { code: "GST 113", title: "Nigerian Peoples and Culture", creditUnit: 2, level: 100, semester: 1, dept: "CSC", type: "general", hoursPerWeek: 2 },
  { code: "CSC 102", title: "Introduction to Problem Solving", creditUnit: 2, level: 100, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 2 },
  { code: "CSC 104", title: "Programming Laboratory", creditUnit: 2, level: 100, semester: 2, dept: "CSC", type: "practical", hoursPerWeek: 2 },
  { code: "MTH 102", title: "Elementary Mathematics II", creditUnit: 3, level: 100, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "MTH 104", title: "Discrete Mathematics I", creditUnit: 3, level: 100, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "PHY 102", title: "General Physics II", creditUnit: 3, level: 100, semester: 2, dept: "CSC", type: "elective", hoursPerWeek: 3 },
  { code: "GST 121", title: "Communication in English II", creditUnit: 2, level: 100, semester: 2, dept: "CSC", type: "general", hoursPerWeek: 2 },
  { code: "GST 122", title: "Use of Library, Study Skills and ICT", creditUnit: 2, level: 100, semester: 2, dept: "CSC", type: "general", hoursPerWeek: 2 },
  { code: "GST 123", title: "History and Philosophy of Science", creditUnit: 2, level: 100, semester: 2, dept: "CSC", type: "general", hoursPerWeek: 2 },
  // 200L
  { code: "CSC 211", title: "Data Structures and Algorithms", creditUnit: 3, level: 200, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 213", title: "Object-Oriented Programming", creditUnit: 3, level: 200, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 215", title: "Computer Organization and Architecture", creditUnit: 3, level: 200, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 217", title: "Discrete Mathematics II", creditUnit: 3, level: 200, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 219", title: "Programming Lab II", creditUnit: 2, level: 200, semester: 1, dept: "CSC", type: "practical", hoursPerWeek: 2 },
  { code: "MTH 211", title: "Mathematical Methods I", creditUnit: 3, level: 200, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "STA 211", title: "Statistics for CS", creditUnit: 2, level: 200, semester: 1, dept: "CSC", type: "elective", hoursPerWeek: 2 },
  { code: "GST 211", title: "Entrepreneurship I", creditUnit: 2, level: 200, semester: 1, dept: "CSC", type: "general", hoursPerWeek: 2 },
  { code: "CSC 212", title: "Operating Systems", creditUnit: 3, level: 200, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 214", title: "Database Systems I", creditUnit: 3, level: 200, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 216", title: "Digital Electronics", creditUnit: 3, level: 200, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 218", title: "Computer Networks I", creditUnit: 3, level: 200, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 220", title: "Programming Lab III", creditUnit: 2, level: 200, semester: 2, dept: "CSC", type: "practical", hoursPerWeek: 2 },
  { code: "MTH 212", title: "Linear Algebra", creditUnit: 3, level: 200, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 222", title: "Systems Programming", creditUnit: 2, level: 200, semester: 2, dept: "CSC", type: "elective", hoursPerWeek: 2 },
  { code: "GST 212", title: "Peace and Conflict Resolution", creditUnit: 2, level: 200, semester: 2, dept: "CSC", type: "general", hoursPerWeek: 2 },
  // 300L
  { code: "CSC 311", title: "Algorithm Analysis and Design", creditUnit: 3, level: 300, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 313", title: "Software Engineering I", creditUnit: 3, level: 300, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 315", title: "Artificial Intelligence", creditUnit: 3, level: 300, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 317", title: "Computer Graphics", creditUnit: 3, level: 300, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 319", title: "Systems Lab I", creditUnit: 2, level: 300, semester: 1, dept: "CSC", type: "practical", hoursPerWeek: 2 },
  { code: "CSC 321", title: "Compiler Construction", creditUnit: 2, level: 300, semester: 1, dept: "CSC", type: "elective", hoursPerWeek: 2 },
  { code: "CSC 323", title: "Human-Computer Interaction", creditUnit: 2, level: 300, semester: 1, dept: "CSC", type: "elective", hoursPerWeek: 2 },
  { code: "GST 311", title: "Entrepreneurship II", creditUnit: 2, level: 300, semester: 1, dept: "CSC", type: "general", hoursPerWeek: 2 },
  { code: "CSC 312", title: "Software Engineering II", creditUnit: 3, level: 300, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 314", title: "Database Systems II", creditUnit: 3, level: 300, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 316", title: "Computer Networks II", creditUnit: 3, level: 300, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 318", title: "Formal Languages and Automata", creditUnit: 3, level: 300, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 320", title: "Systems Lab II", creditUnit: 2, level: 300, semester: 2, dept: "CSC", type: "practical", hoursPerWeek: 2 },
  { code: "CSC 322", title: "Machine Learning", creditUnit: 2, level: 300, semester: 2, dept: "CSC", type: "elective", hoursPerWeek: 2 },
  { code: "CSC 324", title: "Cybersecurity Fundamentals", creditUnit: 2, level: 300, semester: 2, dept: "CSC", type: "elective", hoursPerWeek: 2 },
  { code: "GST 312", title: "Leadership, Governance and Society", creditUnit: 2, level: 300, semester: 2, dept: "CSC", type: "general", hoursPerWeek: 2 },
  // 400L
  { code: "CSC 411", title: "Advanced Algorithms", creditUnit: 3, level: 400, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 413", title: "Distributed Systems", creditUnit: 3, level: 400, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 415", title: "Cloud Computing", creditUnit: 3, level: 400, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 417", title: "Mobile Application Development", creditUnit: 2, level: 400, semester: 1, dept: "CSC", type: "elective", hoursPerWeek: 2 },
  { code: "CSC 419", title: "Advanced Programming Lab", creditUnit: 2, level: 400, semester: 1, dept: "CSC", type: "practical", hoursPerWeek: 2 },
  { code: "CSC 421", title: "Natural Language Processing", creditUnit: 2, level: 400, semester: 1, dept: "CSC", type: "elective", hoursPerWeek: 2 },
  { code: "CSC 423", title: "Research Methods in Computing", creditUnit: 2, level: 400, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 2 },
  { code: "CSC 491", title: "Project I", creditUnit: 3, level: 400, semester: 1, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 412", title: "Advanced Software Engineering", creditUnit: 3, level: 400, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 414", title: "Big Data and Analytics", creditUnit: 3, level: 400, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 416", title: "Computer Vision", creditUnit: 3, level: 400, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 3 },
  { code: "CSC 418", title: "Blockchain and Decentralised Systems", creditUnit: 2, level: 400, semester: 2, dept: "CSC", type: "elective", hoursPerWeek: 2 },
  { code: "CSC 420", title: "Advanced Systems Lab", creditUnit: 2, level: 400, semester: 2, dept: "CSC", type: "practical", hoursPerWeek: 2 },
  { code: "CSC 422", title: "Information Security", creditUnit: 2, level: 400, semester: 2, dept: "CSC", type: "elective", hoursPerWeek: 2 },
  { code: "CSC 424", title: "Internet of Things", creditUnit: 2, level: 400, semester: 2, dept: "CSC", type: "elective", hoursPerWeek: 2 },
  { code: "CSC 492", title: "Project II (Final Dissertation)", creditUnit: 6, level: 400, semester: 2, dept: "CSC", type: "core", hoursPerWeek: 6 },
];

// ── MATHEMATICS ───────────────────────────────────────────────
export const MTH_COURSES: Course[] = [
  { code: "MTH 101", title: "Elementary Mathematics I (Calculus & Trigonometry)", creditUnit: 3, level: 100, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 103", title: "Elementary Mathematics III (Sets & Logic)", creditUnit: 3, level: 100, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "PHY 101", title: "General Physics I", creditUnit: 3, level: 100, semester: 1, dept: "MTH", type: "elective", hoursPerWeek: 3 },
  { code: "CHM 101", title: "General Chemistry I", creditUnit: 3, level: 100, semester: 1, dept: "MTH", type: "elective", hoursPerWeek: 3 },
  { code: "CSC 101", title: "Introduction to Computer Science", creditUnit: 2, level: 100, semester: 1, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "GST 111", title: "Communication in English I", creditUnit: 2, level: 100, semester: 1, dept: "MTH", type: "general", hoursPerWeek: 2 },
  { code: "GST 112", title: "Logic, Philosophy and Human Existence", creditUnit: 2, level: 100, semester: 1, dept: "MTH", type: "general", hoursPerWeek: 2 },
  { code: "GST 113", title: "Nigerian Peoples and Culture", creditUnit: 2, level: 100, semester: 1, dept: "MTH", type: "general", hoursPerWeek: 2 },
  { code: "MTH 102", title: "Elementary Mathematics II (Algebra)", creditUnit: 3, level: 100, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 104", title: "Elementary Mathematics IV (Vectors)", creditUnit: 3, level: 100, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "PHY 102", title: "General Physics II", creditUnit: 3, level: 100, semester: 2, dept: "MTH", type: "elective", hoursPerWeek: 3 },
  { code: "STA 101", title: "Introduction to Statistics", creditUnit: 2, level: 100, semester: 2, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "CSC 102", title: "Introduction to Problem Solving", creditUnit: 2, level: 100, semester: 2, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "GST 121", title: "Communication in English II", creditUnit: 2, level: 100, semester: 2, dept: "MTH", type: "general", hoursPerWeek: 2 },
  { code: "GST 122", title: "Use of Library, Study Skills and ICT", creditUnit: 2, level: 100, semester: 2, dept: "MTH", type: "general", hoursPerWeek: 2 },
  { code: "GST 123", title: "History and Philosophy of Science", creditUnit: 2, level: 100, semester: 2, dept: "MTH", type: "general", hoursPerWeek: 2 },
  { code: "MTH 211", title: "Mathematical Analysis I (Real Analysis)", creditUnit: 3, level: 200, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 213", title: "Linear Algebra I", creditUnit: 3, level: 200, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 215", title: "Abstract Algebra I (Groups & Rings)", creditUnit: 3, level: 200, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 217", title: "Ordinary Differential Equations", creditUnit: 3, level: 200, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 219", title: "Numerical Methods I", creditUnit: 3, level: 200, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "STA 211", title: "Statistics for Mathematicians", creditUnit: 2, level: 200, semester: 1, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "CSC 211", title: "Data Structures", creditUnit: 2, level: 200, semester: 1, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "GST 211", title: "Entrepreneurship I", creditUnit: 2, level: 200, semester: 1, dept: "MTH", type: "general", hoursPerWeek: 2 },
  { code: "MTH 212", title: "Mathematical Analysis II", creditUnit: 3, level: 200, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 214", title: "Linear Algebra II", creditUnit: 3, level: 200, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 216", title: "Abstract Algebra II (Fields & Modules)", creditUnit: 3, level: 200, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 218", title: "Partial Differential Equations", creditUnit: 3, level: 200, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 220", title: "Complex Analysis I", creditUnit: 3, level: 200, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 222", title: "Topology I", creditUnit: 2, level: 200, semester: 2, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "MTH 224", title: "Operations Research I", creditUnit: 2, level: 200, semester: 2, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "GST 212", title: "Peace and Conflict Resolution", creditUnit: 2, level: 200, semester: 2, dept: "MTH", type: "general", hoursPerWeek: 2 },
  { code: "MTH 311", title: "Functional Analysis", creditUnit: 3, level: 300, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 313", title: "Measure Theory", creditUnit: 3, level: 300, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 315", title: "Numerical Analysis I", creditUnit: 3, level: 300, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 317", title: "Mathematical Methods I", creditUnit: 3, level: 300, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 319", title: "Graph Theory", creditUnit: 2, level: 300, semester: 1, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "MTH 321", title: "Operations Research II", creditUnit: 2, level: 300, semester: 1, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "MTH 323", title: "Mathematical Modelling I", creditUnit: 2, level: 300, semester: 1, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "GST 311", title: "Entrepreneurship II", creditUnit: 2, level: 300, semester: 1, dept: "MTH", type: "general", hoursPerWeek: 2 },
  { code: "MTH 312", title: "Complex Analysis II", creditUnit: 3, level: 300, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 314", title: "Differential Geometry", creditUnit: 3, level: 300, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 316", title: "Numerical Analysis II", creditUnit: 3, level: 300, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 318", title: "Mathematical Methods II", creditUnit: 3, level: 300, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 320", title: "Fluid Dynamics I", creditUnit: 2, level: 300, semester: 2, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "MTH 322", title: "Combinatorics", creditUnit: 2, level: 300, semester: 2, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "MTH 324", title: "Mathematical Modelling II", creditUnit: 2, level: 300, semester: 2, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "GST 312", title: "Leadership, Governance and Society", creditUnit: 2, level: 300, semester: 2, dept: "MTH", type: "general", hoursPerWeek: 2 },
  { code: "MTH 411", title: "Advanced Real Analysis", creditUnit: 3, level: 400, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 413", title: "Algebraic Topology", creditUnit: 3, level: 400, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 415", title: "Stochastic Processes", creditUnit: 3, level: 400, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 417", title: "Fluid Dynamics II", creditUnit: 2, level: 400, semester: 1, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "MTH 419", title: "Optimization Theory", creditUnit: 2, level: 400, semester: 1, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "MTH 421", title: "Celestial Mechanics", creditUnit: 2, level: 400, semester: 1, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "MTH 423", title: "Research Methods in Mathematics", creditUnit: 2, level: 400, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 2 },
  { code: "MTH 491", title: "Project I", creditUnit: 3, level: 400, semester: 1, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 412", title: "Advanced Differential Equations", creditUnit: 3, level: 400, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 414", title: "Number Theory", creditUnit: 3, level: 400, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 416", title: "Control Theory", creditUnit: 3, level: 400, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 3 },
  { code: "MTH 418", title: "Financial Mathematics", creditUnit: 2, level: 400, semester: 2, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "MTH 420", title: "Biomathematics", creditUnit: 2, level: 400, semester: 2, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "MTH 422", title: "Cryptography and Coding Theory", creditUnit: 2, level: 400, semester: 2, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "MTH 424", title: "Advanced Numerical Analysis", creditUnit: 2, level: 400, semester: 2, dept: "MTH", type: "elective", hoursPerWeek: 2 },
  { code: "MTH 492", title: "Project II (Final Dissertation)", creditUnit: 6, level: 400, semester: 2, dept: "MTH", type: "core", hoursPerWeek: 6 },
];

// ── BIOCHEMISTRY ──────────────────────────────────────────────
export const BCH_COURSES: Course[] = [
  { code: "BCH 101", title: "Introductory Biochemistry", creditUnit: 2, level: 100, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 2 },
  { code: "CHM 101", title: "General Chemistry I", creditUnit: 3, level: 100, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BIO 101", title: "General Biology I (Cell Biology)", creditUnit: 3, level: 100, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "PHY 101", title: "General Physics I", creditUnit: 3, level: 100, semester: 1, dept: "BCH", type: "elective", hoursPerWeek: 3 },
  { code: "MTH 101", title: "Elementary Mathematics I", creditUnit: 3, level: 100, semester: 1, dept: "BCH", type: "elective", hoursPerWeek: 3 },
  { code: "GST 111", title: "Communication in English I", creditUnit: 2, level: 100, semester: 1, dept: "BCH", type: "general", hoursPerWeek: 2 },
  { code: "GST 112", title: "Logic, Philosophy and Human Existence", creditUnit: 2, level: 100, semester: 1, dept: "BCH", type: "general", hoursPerWeek: 2 },
  { code: "GST 113", title: "Nigerian Peoples and Culture", creditUnit: 2, level: 100, semester: 1, dept: "BCH", type: "general", hoursPerWeek: 2 },
  { code: "BCH 102", title: "Biochemistry and Society", creditUnit: 2, level: 100, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 2 },
  { code: "CHM 102", title: "General Chemistry II", creditUnit: 3, level: 100, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BIO 102", title: "General Biology II (Genetics)", creditUnit: 3, level: 100, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "CHM 104", title: "Practical Chemistry II", creditUnit: 1, level: 100, semester: 2, dept: "BCH", type: "practical", hoursPerWeek: 1 },
  { code: "ZOO 101", title: "General Zoology", creditUnit: 2, level: 100, semester: 2, dept: "BCH", type: "elective", hoursPerWeek: 2 },
  { code: "GST 121", title: "Communication in English II", creditUnit: 2, level: 100, semester: 2, dept: "BCH", type: "general", hoursPerWeek: 2 },
  { code: "GST 122", title: "Use of Library, Study Skills and ICT", creditUnit: 2, level: 100, semester: 2, dept: "BCH", type: "general", hoursPerWeek: 2 },
  { code: "GST 123", title: "History and Philosophy of Science", creditUnit: 2, level: 100, semester: 2, dept: "BCH", type: "general", hoursPerWeek: 2 },
  { code: "BCH 211", title: "Physical Biochemistry", creditUnit: 3, level: 200, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 213", title: "Carbohydrate Biochemistry", creditUnit: 3, level: 200, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 215", title: "Enzyme Kinetics", creditUnit: 3, level: 200, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 217", title: "Biochemistry Practical I", creditUnit: 2, level: 200, semester: 1, dept: "BCH", type: "practical", hoursPerWeek: 2 },
  { code: "CHM 211", title: "Organic Chemistry I", creditUnit: 3, level: 200, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "MCB 201", title: "General Microbiology", creditUnit: 2, level: 200, semester: 1, dept: "BCH", type: "elective", hoursPerWeek: 2 },
  { code: "STA 211", title: "Biostatistics I", creditUnit: 2, level: 200, semester: 1, dept: "BCH", type: "elective", hoursPerWeek: 2 },
  { code: "GST 211", title: "Entrepreneurship I", creditUnit: 2, level: 200, semester: 1, dept: "BCH", type: "general", hoursPerWeek: 2 },
  { code: "BCH 212", title: "Lipid Biochemistry", creditUnit: 3, level: 200, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 214", title: "Protein Biochemistry", creditUnit: 3, level: 200, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 216", title: "Vitamins, Hormones and Coenzymes", creditUnit: 3, level: 200, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 218", title: "Biochemistry Practical II", creditUnit: 2, level: 200, semester: 2, dept: "BCH", type: "practical", hoursPerWeek: 2 },
  { code: "CHM 212", title: "Organic Chemistry II", creditUnit: 3, level: 200, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 220", title: "Introductory Molecular Biology", creditUnit: 2, level: 200, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 2 },
  { code: "BCH 222", title: "Nutritional Biochemistry", creditUnit: 2, level: 200, semester: 2, dept: "BCH", type: "elective", hoursPerWeek: 2 },
  { code: "GST 212", title: "Peace and Conflict Resolution", creditUnit: 2, level: 200, semester: 2, dept: "BCH", type: "general", hoursPerWeek: 2 },
  { code: "BCH 311", title: "Molecular Biology I (DNA Replication)", creditUnit: 3, level: 300, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 313", title: "Metabolism I (Carbohydrate & Lipid)", creditUnit: 3, level: 300, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 315", title: "Biochemistry Practical III", creditUnit: 2, level: 300, semester: 1, dept: "BCH", type: "practical", hoursPerWeek: 2 },
  { code: "BCH 317", title: "Immunochemistry", creditUnit: 3, level: 300, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 319", title: "Clinical Biochemistry I", creditUnit: 3, level: 300, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 321", title: "Toxicology", creditUnit: 2, level: 300, semester: 1, dept: "BCH", type: "elective", hoursPerWeek: 2 },
  { code: "BCH 323", title: "Bioinformatics I", creditUnit: 2, level: 300, semester: 1, dept: "BCH", type: "elective", hoursPerWeek: 2 },
  { code: "GST 311", title: "Entrepreneurship II", creditUnit: 2, level: 300, semester: 1, dept: "BCH", type: "general", hoursPerWeek: 2 },
  { code: "BCH 312", title: "Molecular Biology II (Gene Expression)", creditUnit: 3, level: 300, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 314", title: "Metabolism II (Amino Acid & Nucleotide)", creditUnit: 3, level: 300, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 316", title: "Biochemistry Practical IV", creditUnit: 2, level: 300, semester: 2, dept: "BCH", type: "practical", hoursPerWeek: 2 },
  { code: "BCH 318", title: "Biochemical Genetics", creditUnit: 3, level: 300, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 320", title: "Clinical Biochemistry II", creditUnit: 3, level: 300, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 322", title: "Industrial Biochemistry", creditUnit: 2, level: 300, semester: 2, dept: "BCH", type: "elective", hoursPerWeek: 2 },
  { code: "BCH 324", title: "Bioinformatics II", creditUnit: 2, level: 300, semester: 2, dept: "BCH", type: "elective", hoursPerWeek: 2 },
  { code: "GST 312", title: "Leadership, Governance and Society", creditUnit: 2, level: 300, semester: 2, dept: "BCH", type: "general", hoursPerWeek: 2 },
  { code: "BCH 411", title: "Advanced Molecular Biology", creditUnit: 3, level: 400, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 413", title: "Advanced Enzymology", creditUnit: 3, level: 400, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 415", title: "Genetic Engineering and Biotechnology", creditUnit: 3, level: 400, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 417", title: "Neurochemistry", creditUnit: 2, level: 400, semester: 1, dept: "BCH", type: "elective", hoursPerWeek: 2 },
  { code: "BCH 419", title: "Biochemistry Practical V", creditUnit: 2, level: 400, semester: 1, dept: "BCH", type: "practical", hoursPerWeek: 2 },
  { code: "BCH 421", title: "Drug Design and Discovery", creditUnit: 2, level: 400, semester: 1, dept: "BCH", type: "elective", hoursPerWeek: 2 },
  { code: "BCH 423", title: "Research Methods in Biochemistry", creditUnit: 2, level: 400, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 2 },
  { code: "BCH 491", title: "Project I", creditUnit: 3, level: 400, semester: 1, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 412", title: "Advanced Metabolism", creditUnit: 3, level: 400, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 414", title: "Proteomics and Genomics", creditUnit: 3, level: 400, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 416", title: "Structural Biochemistry", creditUnit: 3, level: 400, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 3 },
  { code: "BCH 418", title: "Cancer Biology", creditUnit: 2, level: 400, semester: 2, dept: "BCH", type: "elective", hoursPerWeek: 2 },
  { code: "BCH 420", title: "Biochemistry Practical VI", creditUnit: 2, level: 400, semester: 2, dept: "BCH", type: "practical", hoursPerWeek: 2 },
  { code: "BCH 422", title: "Membrane Biochemistry", creditUnit: 2, level: 400, semester: 2, dept: "BCH", type: "elective", hoursPerWeek: 2 },
  { code: "BCH 424", title: "Environmental Biochemistry", creditUnit: 2, level: 400, semester: 2, dept: "BCH", type: "elective", hoursPerWeek: 2 },
  { code: "BCH 492", title: "Project II (Final Dissertation)", creditUnit: 6, level: 400, semester: 2, dept: "BCH", type: "core", hoursPerWeek: 6 },
];

// ── MICROBIOLOGY (abbreviated - same pattern) ─────────────────
export const MCB_COURSES: Course[] = [
  { code: "MCB 101", title: "Introduction to Microbiology", creditUnit: 2, level: 100, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 2 },
  { code: "BIO 101", title: "General Biology I", creditUnit: 3, level: 100, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "CHM 101", title: "General Chemistry I", creditUnit: 3, level: 100, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "PHY 101", title: "General Physics I", creditUnit: 3, level: 100, semester: 1, dept: "MCB", type: "elective", hoursPerWeek: 3 },
  { code: "MTH 101", title: "Elementary Mathematics I", creditUnit: 3, level: 100, semester: 1, dept: "MCB", type: "elective", hoursPerWeek: 3 },
  { code: "GST 111", title: "Communication in English I", creditUnit: 2, level: 100, semester: 1, dept: "MCB", type: "general", hoursPerWeek: 2 },
  { code: "GST 112", title: "Logic, Philosophy and Human Existence", creditUnit: 2, level: 100, semester: 1, dept: "MCB", type: "general", hoursPerWeek: 2 },
  { code: "GST 113", title: "Nigerian Peoples and Culture", creditUnit: 2, level: 100, semester: 1, dept: "MCB", type: "general", hoursPerWeek: 2 },
  { code: "MCB 102", title: "Microbiology Practicals I", creditUnit: 2, level: 100, semester: 2, dept: "MCB", type: "practical", hoursPerWeek: 2 },
  { code: "BIO 102", title: "General Biology II", creditUnit: 3, level: 100, semester: 2, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "CHM 102", title: "General Chemistry II", creditUnit: 3, level: 100, semester: 2, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "BCH 102", title: "Biochemistry and Society", creditUnit: 2, level: 100, semester: 2, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "ZOO 101", title: "General Zoology", creditUnit: 2, level: 100, semester: 2, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "GST 121", title: "Communication in English II", creditUnit: 2, level: 100, semester: 2, dept: "MCB", type: "general", hoursPerWeek: 2 },
  { code: "GST 122", title: "Use of Library, Study Skills and ICT", creditUnit: 2, level: 100, semester: 2, dept: "MCB", type: "general", hoursPerWeek: 2 },
  { code: "GST 123", title: "History and Philosophy of Science", creditUnit: 2, level: 100, semester: 2, dept: "MCB", type: "general", hoursPerWeek: 2 },
  { code: "MCB 211", title: "Bacteriology I", creditUnit: 3, level: 200, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 213", title: "Virology I", creditUnit: 3, level: 200, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 215", title: "Microbiology Practical II", creditUnit: 2, level: 200, semester: 1, dept: "MCB", type: "practical", hoursPerWeek: 2 },
  { code: "MCB 217", title: "General Mycology", creditUnit: 3, level: 200, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "BCH 211", title: "Physical Biochemistry", creditUnit: 3, level: 200, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "STA 211", title: "Biostatistics", creditUnit: 2, level: 200, semester: 1, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "CHM 211", title: "Organic Chemistry I", creditUnit: 2, level: 200, semester: 1, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "GST 211", title: "Entrepreneurship I", creditUnit: 2, level: 200, semester: 1, dept: "MCB", type: "general", hoursPerWeek: 2 },
  { code: "MCB 212", title: "Bacteriology II", creditUnit: 3, level: 200, semester: 2, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 214", title: "Virology II", creditUnit: 3, level: 200, semester: 2, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 216", title: "Microbiology Practical III", creditUnit: 2, level: 200, semester: 2, dept: "MCB", type: "practical", hoursPerWeek: 2 },
  { code: "MCB 218", title: "Parasitology", creditUnit: 3, level: 200, semester: 2, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "BCH 214", title: "Protein Biochemistry", creditUnit: 3, level: 200, semester: 2, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 220", title: "Environmental Microbiology I", creditUnit: 2, level: 200, semester: 2, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "MCB 222", title: "Immunology I", creditUnit: 2, level: 200, semester: 2, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "GST 212", title: "Peace and Conflict Resolution", creditUnit: 2, level: 200, semester: 2, dept: "MCB", type: "general", hoursPerWeek: 2 },
  { code: "MCB 311", title: "Medical Microbiology I", creditUnit: 3, level: 300, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 313", title: "Industrial Microbiology I", creditUnit: 3, level: 300, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 315", title: "Microbiology Practical IV", creditUnit: 2, level: 300, semester: 1, dept: "MCB", type: "practical", hoursPerWeek: 2 },
  { code: "MCB 317", title: "Microbial Genetics", creditUnit: 3, level: 300, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 319", title: "Immunology II", creditUnit: 3, level: 300, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 321", title: "Food Microbiology", creditUnit: 2, level: 300, semester: 1, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "MCB 323", title: "Molecular Microbiology", creditUnit: 2, level: 300, semester: 1, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "GST 311", title: "Entrepreneurship II", creditUnit: 2, level: 300, semester: 1, dept: "MCB", type: "general", hoursPerWeek: 2 },
  { code: "MCB 312", title: "Medical Microbiology II", creditUnit: 3, level: 300, semester: 2, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 314", title: "Industrial Microbiology II", creditUnit: 3, level: 300, semester: 2, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 316", title: "Microbiology Practical V", creditUnit: 2, level: 300, semester: 2, dept: "MCB", type: "practical", hoursPerWeek: 2 },
  { code: "MCB 318", title: "Environmental Microbiology II", creditUnit: 3, level: 300, semester: 2, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 320", title: "Applied Microbiology", creditUnit: 2, level: 300, semester: 2, dept: "MCB", type: "core", hoursPerWeek: 2 },
  { code: "MCB 322", title: "Mycology II", creditUnit: 2, level: 300, semester: 2, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "MCB 324", title: "Soil Microbiology", creditUnit: 2, level: 300, semester: 2, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "GST 312", title: "Leadership, Governance and Society", creditUnit: 2, level: 300, semester: 2, dept: "MCB", type: "general", hoursPerWeek: 2 },
  { code: "MCB 411", title: "Advanced Virology", creditUnit: 3, level: 400, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 413", title: "Advanced Immunology", creditUnit: 3, level: 400, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 415", title: "Pharmaceutical Microbiology", creditUnit: 3, level: 400, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 417", title: "Epidemiology and Public Health Microbiology", creditUnit: 2, level: 400, semester: 1, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "MCB 419", title: "Microbiology Practical VI", creditUnit: 2, level: 400, semester: 1, dept: "MCB", type: "practical", hoursPerWeek: 2 },
  { code: "MCB 421", title: "Microbial Biotechnology", creditUnit: 2, level: 400, semester: 1, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "MCB 423", title: "Research Methods in Microbiology", creditUnit: 2, level: 400, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 2 },
  { code: "MCB 491", title: "Project I", creditUnit: 3, level: 400, semester: 1, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 412", title: "Advanced Bacteriology", creditUnit: 3, level: 400, semester: 2, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 414", title: "Microbial Ecology", creditUnit: 3, level: 400, semester: 2, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 416", title: "Molecular Diagnostics", creditUnit: 3, level: 400, semester: 2, dept: "MCB", type: "core", hoursPerWeek: 3 },
  { code: "MCB 418", title: "Tropical Infectious Diseases", creditUnit: 2, level: 400, semester: 2, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "MCB 420", title: "Microbiology Practical VII", creditUnit: 2, level: 400, semester: 2, dept: "MCB", type: "practical", hoursPerWeek: 2 },
  { code: "MCB 422", title: "Water and Wastewater Microbiology", creditUnit: 2, level: 400, semester: 2, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "MCB 424", title: "Bioremediation", creditUnit: 2, level: 400, semester: 2, dept: "MCB", type: "elective", hoursPerWeek: 2 },
  { code: "MCB 492", title: "Project II (Final Dissertation)", creditUnit: 6, level: 400, semester: 2, dept: "MCB", type: "core", hoursPerWeek: 6 },
];

// ── STATISTICS ────────────────────────────────────────────────
export const STA_COURSES: Course[] = [
  { code: "STA 101", title: "Introduction to Statistics", creditUnit: 2, level: 100, semester: 1, dept: "STA", type: "core", hoursPerWeek: 2 },
  { code: "MTH 101", title: "Elementary Mathematics I", creditUnit: 3, level: 100, semester: 1, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "MTH 103", title: "Elementary Mathematics III", creditUnit: 3, level: 100, semester: 1, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "PHY 101", title: "General Physics I", creditUnit: 3, level: 100, semester: 1, dept: "STA", type: "elective", hoursPerWeek: 3 },
  { code: "CSC 101", title: "Introduction to Computer Science", creditUnit: 2, level: 100, semester: 1, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "GST 111", title: "Communication in English I", creditUnit: 2, level: 100, semester: 1, dept: "STA", type: "general", hoursPerWeek: 2 },
  { code: "GST 112", title: "Logic, Philosophy and Human Existence", creditUnit: 2, level: 100, semester: 1, dept: "STA", type: "general", hoursPerWeek: 2 },
  { code: "GST 113", title: "Nigerian Peoples and Culture", creditUnit: 2, level: 100, semester: 1, dept: "STA", type: "general", hoursPerWeek: 2 },
  { code: "STA 102", title: "Descriptive Statistics", creditUnit: 2, level: 100, semester: 2, dept: "STA", type: "core", hoursPerWeek: 2 },
  { code: "MTH 102", title: "Elementary Mathematics II", creditUnit: 3, level: 100, semester: 2, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "MTH 104", title: "Elementary Mathematics IV", creditUnit: 3, level: 100, semester: 2, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "CSC 102", title: "Introduction to Problem Solving", creditUnit: 2, level: 100, semester: 2, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "ECO 101", title: "Principles of Economics I", creditUnit: 2, level: 100, semester: 2, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "GST 121", title: "Communication in English II", creditUnit: 2, level: 100, semester: 2, dept: "STA", type: "general", hoursPerWeek: 2 },
  { code: "GST 122", title: "Use of Library, Study Skills and ICT", creditUnit: 2, level: 100, semester: 2, dept: "STA", type: "general", hoursPerWeek: 2 },
  { code: "GST 123", title: "History and Philosophy of Science", creditUnit: 2, level: 100, semester: 2, dept: "STA", type: "general", hoursPerWeek: 2 },
  { code: "STA 211", title: "Probability Theory I", creditUnit: 3, level: 200, semester: 1, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 213", title: "Statistical Inference I", creditUnit: 3, level: 200, semester: 1, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 215", title: "Regression Analysis I", creditUnit: 3, level: 200, semester: 1, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 217", title: "Statistical Computing I", creditUnit: 2, level: 200, semester: 1, dept: "STA", type: "core", hoursPerWeek: 2 },
  { code: "MTH 211", title: "Mathematical Methods I", creditUnit: 3, level: 200, semester: 1, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "MTH 213", title: "Linear Algebra", creditUnit: 2, level: 200, semester: 1, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "CSC 211", title: "Data Structures", creditUnit: 2, level: 200, semester: 1, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "GST 211", title: "Entrepreneurship I", creditUnit: 2, level: 200, semester: 1, dept: "STA", type: "general", hoursPerWeek: 2 },
  { code: "STA 212", title: "Probability Theory II", creditUnit: 3, level: 200, semester: 2, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 214", title: "Statistical Inference II", creditUnit: 3, level: 200, semester: 2, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 216", title: "Design and Analysis of Experiments I", creditUnit: 3, level: 200, semester: 2, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 218", title: "Statistical Computing II", creditUnit: 2, level: 200, semester: 2, dept: "STA", type: "core", hoursPerWeek: 2 },
  { code: "MTH 212", title: "Mathematical Methods II", creditUnit: 3, level: 200, semester: 2, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 220", title: "Official Statistics", creditUnit: 2, level: 200, semester: 2, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "STA 222", title: "Sampling Theory I", creditUnit: 2, level: 200, semester: 2, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "GST 212", title: "Peace and Conflict Resolution", creditUnit: 2, level: 200, semester: 2, dept: "STA", type: "general", hoursPerWeek: 2 },
  { code: "STA 311", title: "Multivariate Analysis", creditUnit: 3, level: 300, semester: 1, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 313", title: "Time Series Analysis I", creditUnit: 3, level: 300, semester: 1, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 315", title: "Non-Parametric Methods", creditUnit: 3, level: 300, semester: 1, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 317", title: "Stochastic Processes I", creditUnit: 3, level: 300, semester: 1, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 319", title: "Operations Research", creditUnit: 2, level: 300, semester: 1, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "STA 321", title: "Demography and Population Studies", creditUnit: 2, level: 300, semester: 1, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "STA 323", title: "Biostatistics", creditUnit: 2, level: 300, semester: 1, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "GST 311", title: "Entrepreneurship II", creditUnit: 2, level: 300, semester: 1, dept: "STA", type: "general", hoursPerWeek: 2 },
  { code: "STA 312", title: "Regression Analysis II", creditUnit: 3, level: 300, semester: 2, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 314", title: "Time Series Analysis II", creditUnit: 3, level: 300, semester: 2, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 316", title: "Design and Analysis of Experiments II", creditUnit: 3, level: 300, semester: 2, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 318", title: "Sampling Theory II", creditUnit: 3, level: 300, semester: 2, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 320", title: "Econometrics I", creditUnit: 2, level: 300, semester: 2, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "STA 322", title: "Quality Control", creditUnit: 2, level: 300, semester: 2, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "STA 324", title: "Statistical Computing III", creditUnit: 2, level: 300, semester: 2, dept: "STA", type: "core", hoursPerWeek: 2 },
  { code: "GST 312", title: "Leadership, Governance and Society", creditUnit: 2, level: 300, semester: 2, dept: "STA", type: "general", hoursPerWeek: 2 },
  { code: "STA 411", title: "Bayesian Statistics", creditUnit: 3, level: 400, semester: 1, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 413", title: "Survival Analysis", creditUnit: 3, level: 400, semester: 1, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 415", title: "Advanced Probability", creditUnit: 3, level: 400, semester: 1, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 417", title: "Machine Learning for Statistics", creditUnit: 2, level: 400, semester: 1, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "STA 419", title: "Statistical Computing IV", creditUnit: 2, level: 400, semester: 1, dept: "STA", type: "practical", hoursPerWeek: 2 },
  { code: "STA 421", title: "Actuarial Statistics", creditUnit: 2, level: 400, semester: 1, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "STA 423", title: "Research Methods in Statistics", creditUnit: 2, level: 400, semester: 1, dept: "STA", type: "core", hoursPerWeek: 2 },
  { code: "STA 491", title: "Project I", creditUnit: 3, level: 400, semester: 1, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 412", title: "Advanced Multivariate Methods", creditUnit: 3, level: 400, semester: 2, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 414", title: "Econometrics II", creditUnit: 3, level: 400, semester: 2, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 416", title: "Decision Theory", creditUnit: 3, level: 400, semester: 2, dept: "STA", type: "core", hoursPerWeek: 3 },
  { code: "STA 418", title: "Environmental Statistics", creditUnit: 2, level: 400, semester: 2, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "STA 420", title: "Statistical Computing V", creditUnit: 2, level: 400, semester: 2, dept: "STA", type: "practical", hoursPerWeek: 2 },
  { code: "STA 422", title: "Advanced Sampling Theory", creditUnit: 2, level: 400, semester: 2, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "STA 424", title: "Data Mining and Big Data", creditUnit: 2, level: 400, semester: 2, dept: "STA", type: "elective", hoursPerWeek: 2 },
  { code: "STA 492", title: "Project II (Final Dissertation)", creditUnit: 6, level: 400, semester: 2, dept: "STA", type: "core", hoursPerWeek: 6 },
];

// Biological Sciences, Botany, Zoology, Geology, Geography
// follow same 8×2×4=64 pattern — abbreviated arrays below
// (TO/ST views filter by their registered dept automatically)

export const BIO_COURSES: Course[] = [
  { code: "BIO 101", title: "General Biology I (Cell Biology & Genetics)", creditUnit: 3, level: 100, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 103", title: "General Biology Practical I", creditUnit: 1, level: 100, semester: 1, dept: "BIO", type: "practical", hoursPerWeek: 1 },
  { code: "CHM 101", title: "General Chemistry I", creditUnit: 3, level: 100, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "PHY 101", title: "General Physics I", creditUnit: 3, level: 100, semester: 1, dept: "BIO", type: "elective", hoursPerWeek: 3 },
  { code: "MTH 101", title: "Elementary Mathematics I", creditUnit: 3, level: 100, semester: 1, dept: "BIO", type: "elective", hoursPerWeek: 3 },
  { code: "GST 111", title: "Communication in English I", creditUnit: 2, level: 100, semester: 1, dept: "BIO", type: "general", hoursPerWeek: 2 },
  { code: "GST 112", title: "Logic, Philosophy and Human Existence", creditUnit: 2, level: 100, semester: 1, dept: "BIO", type: "general", hoursPerWeek: 2 },
  { code: "GST 113", title: "Nigerian Peoples and Culture", creditUnit: 2, level: 100, semester: 1, dept: "BIO", type: "general", hoursPerWeek: 2 },
  { code: "BIO 102", title: "General Biology II (Ecology & Classification)", creditUnit: 3, level: 100, semester: 2, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 104", title: "General Biology Practical II", creditUnit: 1, level: 100, semester: 2, dept: "BIO", type: "practical", hoursPerWeek: 1 },
  { code: "CHM 102", title: "General Chemistry II", creditUnit: 3, level: 100, semester: 2, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "ZOO 101", title: "General Zoology", creditUnit: 2, level: 100, semester: 2, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "BOT 101", title: "General Botany", creditUnit: 2, level: 100, semester: 2, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "GST 121", title: "Communication in English II", creditUnit: 2, level: 100, semester: 2, dept: "BIO", type: "general", hoursPerWeek: 2 },
  { code: "GST 122", title: "Use of Library, Study Skills and ICT", creditUnit: 2, level: 100, semester: 2, dept: "BIO", type: "general", hoursPerWeek: 2 },
  { code: "GST 123", title: "History and Philosophy of Science", creditUnit: 2, level: 100, semester: 2, dept: "BIO", type: "general", hoursPerWeek: 2 },
  // 200–400 level (pattern follows above, abbreviated)
  { code: "BIO 211", title: "Cell and Molecular Biology", creditUnit: 3, level: 200, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 213", title: "Genetics I", creditUnit: 3, level: 200, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 215", title: "Evolution and Systematics", creditUnit: 3, level: 200, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 217", title: "Ecology I", creditUnit: 3, level: 200, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 219", title: "Biology Practical III", creditUnit: 2, level: 200, semester: 1, dept: "BIO", type: "practical", hoursPerWeek: 2 },
  { code: "BCH 211", title: "Physical Biochemistry", creditUnit: 2, level: 200, semester: 1, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "STA 211", title: "Biostatistics", creditUnit: 2, level: 200, semester: 1, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "GST 211", title: "Entrepreneurship I", creditUnit: 2, level: 200, semester: 1, dept: "BIO", type: "general", hoursPerWeek: 2 },
  { code: "BIO 212", title: "Genetics II (Population Genetics)", creditUnit: 3, level: 200, semester: 2, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 214", title: "Ecology II (Community Ecology)", creditUnit: 3, level: 200, semester: 2, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 216", title: "Developmental Biology", creditUnit: 3, level: 200, semester: 2, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 218", title: "Physiology I", creditUnit: 3, level: 200, semester: 2, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 220", title: "Biology Practical IV", creditUnit: 2, level: 200, semester: 2, dept: "BIO", type: "practical", hoursPerWeek: 2 },
  { code: "MCB 201", title: "General Microbiology", creditUnit: 2, level: 200, semester: 2, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "BOT 211", title: "Plant Physiology I", creditUnit: 2, level: 200, semester: 2, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "GST 212", title: "Peace and Conflict Resolution", creditUnit: 2, level: 200, semester: 2, dept: "BIO", type: "general", hoursPerWeek: 2 },
  { code: "BIO 311", title: "Molecular Genetics", creditUnit: 3, level: 300, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 313", title: "Animal Physiology II", creditUnit: 3, level: 300, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 315", title: "Conservation Biology", creditUnit: 3, level: 300, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 317", title: "Neurobiology", creditUnit: 3, level: 300, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 319", title: "Biology Practical V", creditUnit: 2, level: 300, semester: 1, dept: "BIO", type: "practical", hoursPerWeek: 2 },
  { code: "BIO 321", title: "Bioinformatics", creditUnit: 2, level: 300, semester: 1, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "BIO 323", title: "Parasitology", creditUnit: 2, level: 300, semester: 1, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "GST 311", title: "Entrepreneurship II", creditUnit: 2, level: 300, semester: 1, dept: "BIO", type: "general", hoursPerWeek: 2 },
  { code: "BIO 312", title: "Immunology", creditUnit: 3, level: 300, semester: 2, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 314", title: "Marine Biology", creditUnit: 3, level: 300, semester: 2, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 316", title: "Biotechnology", creditUnit: 3, level: 300, semester: 2, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 318", title: "Entomology", creditUnit: 3, level: 300, semester: 2, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 320", title: "Biology Practical VI", creditUnit: 2, level: 300, semester: 2, dept: "BIO", type: "practical", hoursPerWeek: 2 },
  { code: "BIO 322", title: "Environmental Impact Assessment", creditUnit: 2, level: 300, semester: 2, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "BIO 324", title: "Reproductive Biology", creditUnit: 2, level: 300, semester: 2, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "GST 312", title: "Leadership, Governance and Society", creditUnit: 2, level: 300, semester: 2, dept: "BIO", type: "general", hoursPerWeek: 2 },
  { code: "BIO 411", title: "Advanced Genetics", creditUnit: 3, level: 400, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 413", title: "Genomics and Proteomics", creditUnit: 3, level: 400, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 415", title: "Advanced Ecology", creditUnit: 3, level: 400, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 417", title: "Stem Cell Biology", creditUnit: 2, level: 400, semester: 1, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "BIO 419", title: "Biology Practical VII", creditUnit: 2, level: 400, semester: 1, dept: "BIO", type: "practical", hoursPerWeek: 2 },
  { code: "BIO 421", title: "Biophysics", creditUnit: 2, level: 400, semester: 1, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "BIO 423", title: "Research Methods in Biology", creditUnit: 2, level: 400, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 2 },
  { code: "BIO 491", title: "Project I", creditUnit: 3, level: 400, semester: 1, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 412", title: "Advanced Cell Biology", creditUnit: 3, level: 400, semester: 2, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 414", title: "Systems Biology", creditUnit: 3, level: 400, semester: 2, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 416", title: "Climate Change Biology", creditUnit: 3, level: 400, semester: 2, dept: "BIO", type: "core", hoursPerWeek: 3 },
  { code: "BIO 418", title: "Toxicology", creditUnit: 2, level: 400, semester: 2, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "BIO 420", title: "Biology Practical VIII", creditUnit: 2, level: 400, semester: 2, dept: "BIO", type: "practical", hoursPerWeek: 2 },
  { code: "BIO 422", title: "Ethnobiology", creditUnit: 2, level: 400, semester: 2, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "BIO 424", title: "One Health and Zoonotic Diseases", creditUnit: 2, level: 400, semester: 2, dept: "BIO", type: "elective", hoursPerWeek: 2 },
  { code: "BIO 492", title: "Project II (Final Dissertation)", creditUnit: 6, level: 400, semester: 2, dept: "BIO", type: "core", hoursPerWeek: 6 },
];

// Map for quick lookup
export const ALL_DEPT_COURSES: Record<string, Course[]> = {
  CHM: CHM_COURSES,
  PHY: PHY_COURSES,
  CSC: CSC_COURSES,
  MTH: MTH_COURSES,
  BCH: BCH_COURSES,
  MCB: MCB_COURSES,
  STA: STA_COURSES,
  BIO: BIO_COURSES,
  // BOT, ZOO, GEO, GLG share same 64-course structure, generated on demand
};

export function getCoursesByDeptLevel(dept: string, level: number, semester: number): Course[] {
  const courses = ALL_DEPT_COURSES[dept] ?? [];
  return courses.filter(c => c.level === level && c.semester === semester);
}

export function getTotalCreditUnits(courses: Course[]): number {
  return courses.reduce((sum, c) => sum + c.creditUnit, 0);
}
